config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    resources :reviews
  end

  root 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action only: [:show, :edit, :update, :destroy]

  before_action :load_restaurant

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = @restaurant.reviews.all

    @reviews = current_user.reviews.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
 #@review = @restaurant.reviews.where(id: params[:id]).to_a

  def show
     @review = @restaurant.reviews.find(params[:id])
  end


  # GET /reviews/new
  def new
    @review = current_user.reviews.new
  end

  # GET /reviews/1/edit
  def edit
    @review = @restaurant.reviews.find(params[:id])
    @review = current_user.reviews.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = @restaurant.reviews.new(review_params)
    p current_user
    respond_to do |format|
      if @review.save
        format.html { redirect_to [@restaurant, @review], notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    @review = @restaurant.reviews.find(params[:id])
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to [@restaurant, @review], notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = @restaurant.reviews.find(params[:id])
    @review.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_reviews_path(@restaurant), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:body, :rating, :title, :restaurant_id, :user_id)
    end

    def load_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@restaurant, @review]) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :review_body %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating, id: :review_rating %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :review_title %>
  </div>

  <div class="field">
    <%= form.hidden_field :restaurant_id, id: :review_restaurant_id %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, id: :review_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', user_review_path(current_user, @review) %> |
<%= link_to 'Back', user_reviews_path(current_user)  %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Rating</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>

        <td><%= review.title %></td>
        <td><%= review.rating %></td>
        <td><%=review.body.slice(0,100)%></td>
        <td><%= link_to 'Show', restaurant_review_path(@restaurant, review) %></td>
        <td><%= link_to 'Edit', edit_restaurant_review_path(@restaurant, review) %></td>
        <td><%= link_to 'Destroy', [@restaurant, review], confirm: 'Are you sure?', method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_restaurant_review_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', user_reviews_path(current_user) %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>



  <p>
  <strong>Title:</strong>
  <%= @review.title %>
    </p>

  <p>
  <strong>Body:</strong>
  <%= @review.body %>
  </p>

  <p>
  <strong>Rating:</strong>
  <%= @review.rating %>
  </p>



<%= link_to 'Edit', edit_restaurant_review_path(@restaurant, @review) %> |
<%= link_to 'Back', restaurant_reviews_path(@restaurant) %>